# Generated by Django 4.2.6 on 2023-10-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('Registro', models.IntegerField(primary_key=True, serialize=False)),
                ('Empresa', models.TextField(max_length=15)),
                ('Mes', models.IntegerField()),
                ('ProduccionTotal', models.IntegerField()),
                ('CantidaPiezasConFallas', models.IntegerField()),
            ],
        ),
    ]
